Add size limit to scanf string specifier
While it's tempting to just switch to fgets(), that would require
implementing our own whitespace stripping to match the current
scanf behavior.

Fixes parfait static analysis warning:
Error: Buffer overrun
   Buffer overflow (CWE 120): Use of fscanf(%s), with buffer 'buf'
        at line 135 of app/xsm/lock.c in function 'GetLockId'.

[ This bug was found by the Parfait 0.3.7 bug checking tool.
  For more information see http://labs.oracle.com/projects/parfait/ ]

Signed-off-by: Alan Coopersmith <alan.coopersmith@oracle.com>
Reviewed-by: Jeremy Huddleston <jeremyhu@apple.com>